services:
  api:
    build: .
    container_name: django_api
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - django_redis
      - db

  django_redis:
    image: redis:latest
    container_name: django_redis
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    container_name: django_db
    restart: always
    environment:
      POSTGRES_USER: django
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - .dbdata:/var/lib/postgresql/data

